version: "3.9"

services:
  api-service:
    container_name: api-service
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8081:8080
    networks:
      - backend
networks:
  backend:
    driver: bridge